version: "3.8"

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      APP_ENV: local
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8090:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3340:3306"
    environment:
      MYSQL_DATABASE: api_backends
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  queue:
    build:
      context: .
    container_name: queue_worker
    command: php artisan queue:work --tries=3
    volumes:
      - .:/var/www
    depends_on:
      - app

volumes:
  dbdata:
