version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_DATABASE: api_backends
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_backends
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped

volumes:
  dbdata:
